version: '3.1'

services:
  db:
    container_name: notepaddb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: notepad
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_4321
    ports:
      - 7531:5432
